version: "3"

services:
  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
      - mqtt
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
      MQTT_BROKER: mqtt
      MQTT_PORT: 1883
      MQTT_TOPIC: rfid/scans
    volumes:
      - ./app:/app
    command: ["python", "-u", "main.py"]

  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config

volumes:
  mysql_data:
