services:
  door-node:
    build: ./app
    container_name: door_node
    restart: unless-stopped
    # Environment variables can optionally override config file values
    # environment:
    #   MQTT_BROKER: "192.168.1.100"  # Override config file if needed
    #   SERIAL_PORT: "/dev/ttyACM0"    # Override if different USB port needed
    
    volumes:
      - ./config:/app/config:ro
      
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Arduino USB connection
      
    # Alternative for different USB ports:
    # devices:
    #   - "/dev/ttyACM0:/dev/ttyACM0"
    
    privileged: false  # Keep minimal privileges
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import json; print(json.dumps({'status': 'healthy'}))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s