services:
  door-node:
    build: ./app
    container_name: door_node
    restart: unless-stopped
    privileged: true
    
    volumes:
      - ./config:/app/config:ro
      
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      
    environment:
      - PYTHONUNBUFFERED=1